In [1]:
import numpy as np
import pandas as pd

In [92]:
def linear_regression(x,y,n_iters = 1000, neta = 0.2):
    n = x.shape[0]
    x = np.hstack((x, np.ones((len(x),1))) ) 
    y = np.reshape(-1,1)
    
    
    def gradient(x,y,weights):
        y_hat = np.dot(x,weights)
        diff = y_hat - y
        grad = np.dot(x.T, diff)
        return 2*grad/n
    
    def gradient_descent(x,y):
        weights = np.random.randn(x.shape[1],1)
        for _ in range(n_iters):
            grad = gradient(x,y,weights)
            weights = weights - neta * grad  
        return weights
    w = gradient_descent(x,y)
    return w

t = linear_regression(x,y)
t.round(3)

array([[ 1.016],
       [ 0.   ],
       [ 0.   ],
       [ 0.   ],
       [-0.   ],
       [ 1.016],
       [ 0.   ],
       [-0.   ],
       [-0.   ],
       [ 0.   ],
       [ 0.   ],
       [ 0.   ],
       [ 0.   ],
       [ 0.   ],
       [ 0.   ],
       [-0.   ],
       [-0.   ],
       [-1.   ]])

In [95]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression

In [97]:
lr = LinearRegression()
lr.fit(x,y)
lr.coef_.round(2)

array([ 3.11997857e+10, -2.00000000e-02, -5.00000000e-02,  3.00000000e-02,
        3.00000000e-02,  3.11997857e+10,  6.00000000e-02,  7.90000000e-01,
       -2.00000000e-02, -0.00000000e+00,  1.00000000e-02,  1.00000000e-02,
        0.00000000e+00, -2.00000000e-02, -1.00000000e-02, -2.00000000e-02,
       -3.00000000e-02])

In [6]:
df = pd.read_csv('cars24-car-price-clean.csv')
df.head()

selling_price      year  km_driven   mileage    engine  max_power  \
0      -1.111046 -0.801317   1.195828  0.045745 -1.310754  -1.157780   
1      -0.223944  0.450030  -0.737872 -0.140402 -0.537456  -0.360203   
2      -0.915058 -1.426990   0.035608 -0.582501 -0.537456  -0.404885   
3      -0.892365 -0.801317  -0.409143  0.329620 -0.921213  -0.693085   
4      -0.182683  0.137194  -0.544502  0.760085  0.042999   0.010435   

        age      make     model  Individual  Trustmark Dealer    Diesel  \
0  0.801317 -0.433854 -1.125683    1.248892         -0.098382 -0.985275   
1 -0.450030 -0.327501 -0.333227    1.248892         -0.098382 -0.985275   
2  1.426990 -0.327501 -0.789807    1.248892         -0.098382 -0.985275   
3  0.801317 -0.433854 -0.905265    1.248892         -0.098382 -0.985275   
4 -0.137194 -0.246579 -0.013096   -0.800710         -0.098382  1.014945   

   Electric       LPG    Petrol    Manual         5        >5  
0 -0.020095 -0.056917  1.024622  0.495818  0.444503 -0.424728  
1 -0.020095 -0.056917  1.024622  0.495818  0.444503 -0.424728  
2 -0.020095 -0.056917  1.024622  0.495818  0.444503 -0.424728  
3 -0.020095 -0.056917  1.024622  0.495818  0.444503 -0.424728  
4 -0.020095 -0.056917 -0.975970  0.495818  0.444503 -0.424728

In [9]:
x = df.drop('selling_price',axis = 1).values
y = df['selling_price'].values

In [93]:
x

array([[-8.01316544e-01,  1.19582817e+00,  4.57451688e-02, ...,
         4.95818203e-01,  4.44503185e-01, -4.24728453e-01],
       [ 4.50030281e-01, -7.37872078e-01, -1.40401980e-01, ...,
         4.95818203e-01,  4.44503185e-01, -4.24728453e-01],
       [-1.42698996e+00,  3.56080197e-02, -5.82501459e-01, ...,
         4.95818203e-01,  4.44503185e-01, -4.24728453e-01],
       ...,
       [ 1.37193575e-01,  1.70967037e-01,  3.80810037e-01, ...,
         4.95818203e-01,  4.44503185e-01, -4.24728453e-01],
       [ 4.50030281e-01,  7.23559971e+01, -8.15185395e-01, ...,
         4.95818203e-01, -2.24970266e+00,  2.35444551e+00],
       [ 1.38854040e+00, -8.73231095e-01, -3.49817523e-01, ...,
        -2.01686827e+00,  4.44503185e-01, -4.24728453e-01]])